### ISSUE TITLE
Watch App hangs on load

### ISSUE THREAD

**Issue by tymrtn** [shu223/watchOS-2-Sampler#13]
This would be a pretty awesome sampler app... if I can get it to work. :)

Running XCode 7 beta 5. Followed the build instructions: updated teams, set up health kit, app groups and edited AudioRecAndPlayInterfaceController, and even went into the app's plist to update the WKCompanionAppBundleIdentifier (not in built instructions).

Unfortunately the watch app hangs when it's run. The iOS app runs fine, but can't reach the watch. Break points in the watch app's delegate don't break. I made a gif to demonstrate: http://cl.ly/image/140q2J2c0M3m

Would love some insight into what might be happening. Thanks!

**Comment by y-shih** [comment]
Same issue on real device.

**Comment by anushkmittal** [comment]
same issue...

**Comment by shu223** [comment]
Please try on public released version.
