### ISSUE TITLE
Close this repo

### ISSUE THREAD

**Issue by jpike88** [shu223/watchOS-2-Sampler#18]
It's broken, and is just going to confuse more people

**Comment by shu223** [comment]
@jpike88 Why do you think so? Where is broken? How confuse people?

**Comment by apoorvnarang** [comment]
The iPhone app keeps on crashing.

**Comment by shu223** [comment]
@apoorvnarang it haven't crashed on my iphone. please create another new issue and write details.

**Comment by jpike88** [comment]
Dude it's a piece of crap, its buggy as hell. Do everyone a favour and either do some proper testing on it, or pull it down.
