### ISSUE TITLE
FinishLauching

### ISSUE THREAD

**Issue by strevg** [shu223/watchOS-2-Sampler#2]
When I run watchOS2Sampler WatchKit app on iPhone6 + Apple Watch, The app crached and writes in the logs: "Extension [2153:56375] Extension received request to wake up for complication support applicationDidFinishLaunching"

**Comment by shu223** [comment]
Sorry, I don't know why...I and My friends can launch this app without that problem...

**Comment by strevg** [comment]
Maybe xcode was not installed correctly...
